package com.bistro.sagg.core.session;

public interface SaggSessionConstants {

	String CURRENT_FRANCHISE_BANCH = "CURRENT_FRANCHISE_BANCH";
	String CURRENT_FRANCHISE_BANCH_COUNTRY = "CURRENT_FRANCHISE_BANCH_COUNTRY";
	String ACTIVE_USER = "ACTIVE_USER";
	String CURRENCY = "CURRENCY";
	String DATE_FORMATTER = "DATE_FORMATTER";
	String SHORT_DATE_FORMATTER = "SHORT_DATE_FORMATTER";
	
}
